rules:
  no-debugger:
    - 0
  no-console:
    - 0
  no-unused-vars:
    - 2
  no-trailing-spaces:
    - 2
  react/jsx-uses-vars:
    - 1
  react/jsx-no-undef:
    - 1
  react/jsx-uses-react:
    - 1
  react/jsx-no-bind:
    - 2
  react/prefer-stateless-function:
    - 2
  react/self-closing-comp:
    - 2
  react/no-string-refs:
    - 1
  no-useless-constructor:
    - 2
  indent:
    - 2
    - 2
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - always
  eol-last:
    - 2
    - always
  array-bracket-spacing:
    - 2
    - never
  object-curly-spacing:
    - 2
    - always
env:
  es6: true
  browser: true
  node: true
  mocha: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true
    experimentalObjectRestSpread: true
    modules: true
    arrowFunctions: true
    classes: true
plugins:
  - react
